SOURCES	+= tpcsim.cpp TPCSimQT.cpp 
HEADERS	+= tpcsim.h 
######################################################################
# Automatically generated by qmake (1.03a) Tue Nov 2 12:17:18 2004
######################################################################


# Input
FORMS	= form1.ui 
TEMPLATE	=app
DBFILE	= TPCSimQT.db
LANGUAGE	= C++
